from pathlib import Path


def replace_once(path, old, new, label):
    p = Path(path)
    s = p.read_text()
    if old not in s:
        raise SystemExit(f"missing target: {label}")
    p.write_text(s.replace(old, new, 1))

proposal_old = '''function consumeRejectedRecognizedPromise(promise) {\n  (async function consumeM13RejectedPromise() {\n    try {\n      await promise;\n    } catch {\n      // Rejection is intentionally consumed before the public boundary fails closed.\n    }\n  })();\n  return true;\n}\n'''
proposal_new = '''function inheritedConstructorUsesSafeDefaultSpecies(promise) {\n  let prototype = getPrototypeOf(promise);\n  while (prototype !== null) {\n    if (isProxy(prototype) === true) return false;\n    const constructorDescriptor = getOwnPropertyDescriptor(prototype, "constructor");\n    if (constructorDescriptor !== undefined) {\n      if ("get" in constructorDescriptor || "set" in constructorDescriptor) return false;\n      const constructor = constructorDescriptor.value;\n      if (constructor === undefined) return true;\n      const objectConstructorDescriptor = getOwnPropertyDescriptor(objectPrototype, "constructor");\n      const objectConstructor =\n        objectConstructorDescriptor !== undefined &&\n        !("get" in objectConstructorDescriptor) &&\n        !("set" in objectConstructorDescriptor)\n          ? objectConstructorDescriptor.value\n          : null;\n      if (constructor !== objectConstructor || typeof constructor !== "function" || isProxy(constructor) === true) {\n        return false;\n      }\n      const speciesDescriptor = getOwnPropertyDescriptor(constructor, promiseSpecies);\n      return speciesDescriptor === undefined;\n    }\n    prototype = getPrototypeOf(prototype);\n  }\n  return true;\n}\n\nfunction consumeRejectedRecognizedPromise(promise) {\n  const previousConstructor = getOwnPropertyDescriptor(promise, "constructor");\n  if (\n    previousConstructor !== undefined &&\n    previousConstructor.configurable !== true\n  ) {\n    if (!trustedPromiseConstructorDescriptor(previousConstructor)) return false;\n    reflectApply(promiseThen, promise, [undefined, () => {}]);\n    return true;\n  }\n  if (\n    previousConstructor === undefined &&\n    isExtensible(promise) !== true\n  ) {\n    if (!inheritedConstructorUsesSafeDefaultSpecies(promise)) return false;\n    reflectApply(promiseThen, promise, [undefined, () => {}]);\n    return true;\n  }\n  defineProperty(promise, "constructor", {\n    value: safePromiseSpeciesContainer,\n    writable: true,\n    enumerable: false,\n    configurable: true\n  });\n  let consumed = false;\n  try {\n    reflectApply(promiseThen, promise, [undefined, () => {}]);\n    consumed = true;\n  } finally {\n    if (previousConstructor === undefined) {\n      if (deleteProperty(promise, "constructor") !== true) consumed = false;\n    } else {\n      try {\n        defineProperty(promise, "constructor", previousConstructor);\n      } catch {\n        consumed = false;\n      }\n    }\n  }\n  return consumed;\n}\n'''
replace_once(
    "src/contract-protection-proposal.js",
    proposal_old,
    proposal_new,
    "proposal safe unshadowable rejection consumption"
)

provider_old = '''function consumeRejectedRecognizedPromise(promise) {\n  (async function consumeM13TransportRejection() {\n    try {\n      await promise;\n    } catch {\n      // Rejection is intentionally consumed before reporting the boundary failure.\n    }\n  })();\n  return true;\n}\n'''
provider_new = '''function inheritedConstructorUsesSafeDefaultSpecies(promise) {\n  let prototype = getPrototypeOf(promise);\n  while (prototype !== null) {\n    if (isProxy(prototype)) return false;\n    const constructorDescriptor = getOwnPropertyDescriptor(prototype, "constructor");\n    if (constructorDescriptor !== undefined) {\n      if ("get" in constructorDescriptor || "set" in constructorDescriptor) return false;\n      const constructor = constructorDescriptor.value;\n      if (constructor === undefined) return true;\n      const objectConstructorDescriptor = getOwnPropertyDescriptor(objectPrototype, "constructor");\n      const objectConstructor =\n        objectConstructorDescriptor !== undefined &&\n        !("get" in objectConstructorDescriptor) &&\n        !("set" in objectConstructorDescriptor)\n          ? objectConstructorDescriptor.value\n          : null;\n      if (constructor !== objectConstructor || typeof constructor !== "function" || isProxy(constructor)) {\n        return false;\n      }\n      const speciesDescriptor = getOwnPropertyDescriptor(constructor, promiseSpecies);\n      return speciesDescriptor === undefined;\n    }\n    prototype = getPrototypeOf(prototype);\n  }\n  return true;\n}\n\nfunction consumeRejectedRecognizedPromise(promise) {\n  const constructorDescriptor = getOwnPropertyDescriptor(promise, "constructor");\n  if (\n    constructorDescriptor !== undefined &&\n    constructorDescriptor.configurable !== true\n  ) {\n    if (!constructorDescriptorIsTrusted(constructorDescriptor)) return false;\n    reflectApply(trustedPromiseThen, promise, [undefined, () => {}]);\n    return true;\n  }\n  if (constructorDescriptor === undefined && isExtensible(promise) !== true) {\n    if (!inheritedConstructorUsesSafeDefaultSpecies(promise)) return false;\n    reflectApply(trustedPromiseThen, promise, [undefined, () => {}]);\n    return true;\n  }\n  defineProperty(promise, "constructor", {\n    value: safePromiseConstructor,\n    writable: true,\n    enumerable: false,\n    configurable: true\n  });\n  let consumed = false;\n  try {\n    reflectApply(trustedPromiseThen, promise, [undefined, () => {}]);\n    consumed = true;\n  } finally {\n    if (constructorDescriptor === undefined) {\n      if (deleteProperty(promise, "constructor") !== true) consumed = false;\n    } else {\n      try {\n        defineProperty(promise, "constructor", constructorDescriptor);\n      } catch {\n        consumed = false;\n      }\n    }\n  }\n  return consumed;\n}\n'''
replace_once(
    "src/provider-adapter-m13.js",
    provider_old,
    provider_new,
    "provider safe unshadowable rejection consumption"
)

print("round4 followup prepared")
