from pathlib import Path

path = Path('src/contract-attacks-core.js')
text = path.read_text()
old = '''const experimentIntrinsics =\n  experimentFreeze({\n    isProxy: utilTypes.isProxy,\n    forbiddenProbes: experimentForbiddenProbes,\n    stringConstructor:\n      String,\n    defineProperty:\n      Object.defineProperty,\n    jsonStringify:\n      JSON.stringify,\n    jsonParse:\n      JSON.parse,\n    ArrayConstructor:\n      Array,\n    ArrayPrototype:\n      Array.prototype,\n    ObjectPrototype:\n      Object.prototype\n  });'''
new = '''const experimentIntrinsics =\n  experimentFreeze({\n    isProxy: utilTypes.isProxy,\n    forbiddenProbes: experimentForbiddenProbes,\n    stringConstructor:\n      String,\n    defineProperty:\n      Object.defineProperty,\n    jsonStringify:\n      JSON.stringify,\n    jsonParse:\n      JSON.parse,\n    ArrayConstructor:\n      Array,\n    ArrayPrototype:\n      Array.prototype,\n    ObjectPrototype:\n      Object.prototype,\n    ObjectPrototypeParent:\n      Object.getPrototypeOf(Object.prototype),\n    PromiseConstructor:\n      Promise,\n    TypeErrorConstructor:\n      TypeError,\n    getOwnPropertyDescriptors:\n      Object.getOwnPropertyDescriptors,\n    getOwnPropertyDescriptor:\n      Object.getOwnPropertyDescriptor,\n    getPrototypeOf:\n      Object.getPrototypeOf,\n    isExtensible:\n      Object.isExtensible,\n    objectIs:\n      Object.is,\n    ownKeys:\n      Reflect.ownKeys,\n    reflectApply:\n      Reflect.apply,\n    deleteProperty:\n      Reflect.deleteProperty,\n    arrayIsArray:\n      Array.isArray,\n    stringTrim:\n      String.prototype.trim,\n    numberIsFinite:\n      Number.isFinite,\n    numberIsInteger:\n      Number.isInteger,\n    SetConstructor:\n      Set,\n    setHas:\n      Set.prototype.has,\n    setAdd:\n      Set.prototype.add,\n    MapConstructor:\n      Map,\n    mapGet:\n      Map.prototype.get,\n    mapSet:\n      Map.prototype.set\n  });'''
if old not in text:
    raise SystemExit('experimentIntrinsics block not found')
path.write_text(text.replace(old, new, 1))
